# ─────────────────────────────────────────────────────────────
# Script: 04_slave_voyages_convert_data_types.R
# Purpose: Convert key columns to appropriate data types for downstream analysis
# Author: Edward Parlati
# Last updated: April 17, 2025
# Project: Slave Voyages Completeness Assessment
# GitHub: https://github.com/edwardparlati/slave-voyages-completeness-audit
# ─────────────────────────────────────────────────────────────
# Description:
# This script ensures that each variable in the dataset has the appropriate R data type
# (e.g., integer, numeric, character, date, logical). It prepares the dataset for splitting
# into normalized tables and for accurate analysis in SQL and visualization tools.
#
# Key tasks:
# - Apply `as.integer()`, `as.character()`, `as.numeric()`, and `as.Date()` to key columns
# - Build a reusable function for structured type conversion
# - Confirm correct data type conversions using `str()`
#
# Output:
# - `voyages_dataset` with updated and standardized data types
# ─────────────────────────────────────────────────────────────

### Convert data types
convert_data_types <- function(df) { 
  df %>%
    mutate(
      ## voyages_meta_data
      voyage_id = as.integer(voyage_id), 
      evergreen = as.logical(evergreen),
      voyage_grouping_code = as.integer(voyage_grouping_code),
      voyage_grouping = as.integer(voyage_grouping),
      
      ## voyages_ships_nations_owners
      ship_name = as.character(ship_name),
      nationality = as.integer(nationality_code),
      tonnage = as.numeric(tonnage),
      tonnage_type = as.integer(tonnage_type),
      rig_type = as.integer(rig_type),
      gun_count = as.integer(gun_count),
      year_constructed = as.integer(year_constructed),
      construction_place = as.integer(construction_place),
      construction_region = as.integer(construction_region),
      registration_year = as.integer(registration_year),
      registration_place = as.integer(registration_place),
      registration_region = as.integer(registration_region),
      primary_owner = as.character(primary_owner),
      secondary_owner = as.character(secondary_owner),
      tertiary_owner = as.character(tertiary_owner),
      fourth_owner = as.character(fourth_owner),
      fifth_owner = as.character(fifth_owner),
      sixth_owner = as.character(sixth_owner),
      seventh_owner = as.character(seventh_owner),
      eighth_owner = as.character(eighth_owner),
      ninth_owner = as.character(ninth_owner),
      tenth_owner = as.character(tenth_owner),
      eleventh_owner = as.character(eleventh_owner),
      twelfth_owner = as.character(twelfth_owner),
      thirteenth_owner = as.character(thirteenth_owner),
      fourteenth_owner = as.character(fourteenth_owner),
      fifteenth_owner = as.character(fifteenth_owner),
      sixteenth_owner = as.character(sixteenth_owner),
      nationality_imputed = as.integer(nationality_imputed),
      tonnage_imputed = as.integer(tonnage_imputed),
      
      ## voyages_outcomes
      voyage_outcome_code = as.integer(voyage_outcome_code),
      slave_outcome_code = as.integer(slave_outcome_code),
      capture_outcome_code = as.integer(capture_outcome_code),
      owner_outcome_code = as.integer(owner_outcome_code),
      african_resistance_outcome_code = as.integer(african_resistance_outcome_code),
      
      ## voyages_itinerary
      departure_port = as.integer(departure_port),
      primary_embark_port = as.integer(primary_embark_port),
      secondary_embark_port = as.integer(secondary_embark_port),
      primary_embark_region = as.integer(primary_embark_region),
      secondary_embark_region = as.integer(secondary_embark_region),
      primary_disembark_port = as.integer(primary_disembark_port),
      secondary_disembark_port = as.integer(secondary_disembark_port),
      primary_disembark_region = as.integer(primary_disembark_region),
      secondary_disembark_region = as.integer(secondary_disembark_region),
      num_ports_before_purchase = as.integer(num_ports_before_purchase),
      primary_purchase_location = as.integer(primary_purchase_location),
      secondary_purchase_location = as.integer(secondary_purchase_location),
      tertiary_purchase_location = as.integer(tertiary_purchase_location),
      embark_region_1 = as.integer(embark_region_1),
      embark_region_2 = as.integer(embark_region_2),
      embark_region_3 = as.integer(embark_region_3),
      port_before_crossing = as.integer(port_before_crossing),
      num_ports_americas_before_sale = as.integer(num_ports_americas_before_sale),
      primary_sale_location = as.integer(primary_sale_location),
      secondary_sale_location = as.integer(secondary_sale_location),
      tertiary_sale_location = as.integer(tertiary_sale_location),
      disembark_region_1 = as.integer(disembark_region_1),
      disembark_region_2 = as.integer(disembark_region_2),
      disembark_region_3 = as.integer(disembark_region_3),
      return_port = as.integer(return_port),
      return_region = as.integer(return_region),
      return_broad_region = as.integer(return_broad_region),
      departure_region = as.integer(departure_region),
      departure_broad_region = as.integer(departure_broad_region),
      primary_purchase_port = as.integer(primary_purchase_port),
      primary_sale_port = as.integer(primary_sale_port),
      departure_port_imputed = as.integer(departure_port_imputed),
      purchase_location_imputed_place = as.integer(purchase_location_imputed_place),
      purchase_location_imputed_region = as.integer(purchase_location_imputed_region),
      purchase_location_imputed_broad_region = as.integer(purchase_location_imputed_broad_region),
      disembark_port_imputed_place = as.integer(disembark_port_imputed_place),
      disembark_port_imputed_region = as.integer(disembark_port_imputed_region),
      disembark_port_imputed_broad_region = as.integer(disembark_port_imputed_broad_region),
      
      ## voyages_dates
      voyage_start_day = as.integer(voyage_start_day),
      voyage_start_month = as.integer(voyage_start_month),
      voyage_start_year = as.integer(voyage_start_year),
      slave_purchase_start_day = as.integer(slave_purchase_start_day),
      slave_purchase_start_month = as.integer(slave_purchase_start_month),
      slave_purchase_start_year = as.integer(slave_purchase_start_year),
      departure_from_africa_day = as.integer(departure_from_africa_day),
      departure_from_africa_month = as.integer(departure_from_africa_month),
      departure_from_africa_year = as.integer(departure_from_africa_year),
      primary_landing_day = as.integer(primary_landing_day),
      primary_landing_month = as.integer(primary_landing_month),
      primary_landing_year = as.integer(primary_landing_year),
      secondary_landing_day = as.integer(secondary_landing_day),
      secondary_landing_month = as.integer(secondary_landing_month),
      secondary_landing_year = as.integer(secondary_landing_year),
      tertiary_landing_day = as.integer(tertiary_landing_day),
      tertiary_landing_month = as.integer(tertiary_landing_month),
      tertiary_landing_year = as.integer(tertiary_landing_year),
      return_departure_day = as.integer(return_departure_day),
      return_departure_month = as.integer(return_departure_month),
      return_departure_year = as.integer(return_departure_year),
      voyage_end_day = as.integer(voyage_end_day),
      voyage_end_month = as.integer(voyage_end_month),
      voyage_end_year = as.integer(voyage_end_year),
      voyage_start_date = as.Date(voyage_start_date),
      slave_purchase_date = as.Date(slave_purchase_date),
      departure_from_africa_date = as.Date(departure_from_africa_date),
      primary_landing_date = as.Date(primary_landing_date),
      secondary_landing_date = as.Date(secondary_landing_date),
      tertiary_landing_date = as.Date(tertiary_landing_date),
      return_departure_date = as.Date(return_departure_date),
      voyage_end_date = as.Date(voyage_end_date),
      middle_passage_length_days = as.integer(middle_passage_length_days),
      period_5_year = as.integer(period_5_year),
      period_10_year = as.integer(period_10_year),
      period_25_year = as.integer(period_25_year),
      period_100_year = as.integer(period_100_year),
      voyage_length_home_to_disembarkation_days = as.integer(voyage_length_home_to_disembarkation_days),
      voyage_length_africa_to_disembarkation_days = as.integer(voyage_length_africa_to_disembarkation_days),
      voyage_start_imputed_year = as.integer(voyage_start_imputed_year),
      departure_from_africa_imputed_year = as.integer(departure_from_africa_imputed_year),
      landing_imputed_year = as.integer(landing_imputed_year),
      
      ## voyages_crew
      captain_1_name = as.character(captain_1_name),
      captain_2_name = as.character(captain_2_name),
      captain_3_name = as.character(captain_3_name),
      crew_initial = as.integer(crew_initial),
      crew_after_purchase = as.integer(crew_after_purchase),
      crew_first_landing = as.integer(crew_first_landing),
      crew_return_start = as.integer(crew_return_start),
      crew_final = as.integer(crew_final),
      crew_unspecified = as.integer(crew_unspecified),
      crew_died_pre_africa = as.integer(crew_died_pre_africa),
      crew_died_in_africa = as.integer(crew_died_in_africa),
      crew_died_middle_passage = as.integer(crew_died_middle_passage),
      crew_died_americas = as.integer(crew_died_americas),
      crew_died_return_voyage = as.integer(crew_died_return_voyage),
      crew_died_total = as.integer(crew_died_total),
      crew_deserted_total = as.integer(crew_deserted_total),
      
      ## voyages_slave_numbers
      slaves_intented_first_port = as.integer(slaves_intented_first_port),
      slaves_intented_second_port = as.integer(slaves_intented_second_port),
      slaves_carried_first_port = as.integer(slaves_carried_first_port),
      slaves_carried_second_port = as.integer(slaves_carried_second_port),
      slaves_carried_third_port = as.integer(slaves_carried_third_port),
      slaves_purchased_total = as.integer(slaves_purchased_total),
      slaves_departed_total = as.integer(slaves_departed_total),
      slaves_arrival_first_port = as.integer(slaves_arrival_first_port),
      slaves_disemark_first_port = as.integer(slaves_disemark_first_port),
      slaves_disemark_second_port = as.integer(slaves_disemark_second_port),
      slaves_disemark_third_port = as.integer(slaves_disemark_third_port),
      slaves_embarked_total = as.integer(slaves_embarked_total),
      slaves_disembarked_total = as.integer(slaves_disembarked_total),
      
      ## voyages_slave_characteristics
      men_embark_port1 = as.integer(men_embark_port1),
      women_embark_port1 = as.integer(women_embark_port1),
      boy_embark_port1 = as.integer(boy_embark_port1),
      girl_embark_port1 = as.integer(girl_embark_port1),
      adult_embark_port1 = as.integer(adult_embark_port1),
      child_embark_port1 = as.integer(child_embark_port1),
      infant_embark_port1 = as.integer(infant_embark_port1),
      male_embark_port1 = as.integer(male_embark_port1),
      female_embark_port1 = as.integer(female_embark_port1),      
      men_died_passage = as.integer(men_died_passage),
      women_died_passage = as.integer(women_died_passage),
      boy_died_passage = as.integer(boy_died_passage),
      girl_died_passage = as.integer(girl_died_passage),
      adult_died_passage = as.integer(adult_died_passage),
      child_died_passage = as.integer(child_died_passage),
      infant_died_passage = as.integer(infant_died_passage),
      male_died_passage = as.integer(male_died_passage),
      female_died_passage = as.integer(female_died_passage),
      men_disembark_port1 = as.integer(men_disembark_port1),
      women_disembark_port1 = as.integer(women_disembark_port1),
      boy_disembark_port1 = as.integer(boy_disembark_port1),
      girl_disembark_port1 = as.integer(girl_disembark_port1),
      adult_disembark_port1 = as.integer(adult_disembark_port1),
      child_disembark_port1 = as.integer(child_disembark_port1),
      infant_disembark_port1 = as.integer(infant_disembark_port1),
      male_disembark_port1 = as.integer(male_disembark_port1),
      female_disembark_port1 = as.integer(female_disembark_port1),
      men_embark_port2 = as.integer(men_embark_port2),
      women_embark_port2 = as.integer(women_embark_port2),
      boy_embark_port2 = as.integer(boy_embark_port2),
      girl_embark_port2 = as.integer(girl_embark_port2),
      adult_embark_port2 = as.integer(adult_embark_port2),
      child_embark_port2 = as.integer(child_embark_port2),
      infant_embark_port2 = as.integer(infant_embark_port2),
      male_embark_port2 = as.integer(male_embark_port2),
      female_embark_port2 = as.integer(female_embark_port2),
      men_embark_port3 = as.integer(men_embark_port3),
      women_embark_port3 = as.integer(women_embark_port3),
      boy_embark_port3 = as.integer(boy_embark_port3),
      girl_embark_port3 = as.integer(girl_embark_port3),
      adult_embark_port3 = as.integer(adult_embark_port3),
      child_embark_port3 = as.integer(child_embark_port3),
      infant_embark_port3 = as.integer(infant_embark_port3),
      male_embark_port3 = as.integer(male_embark_port3),
      female_embark_port3 = as.integer(female_embark_port3),
      men_disembark_port2 = as.integer(men_disembark_port2),
      women_disembark_port2 = as.integer(women_disembark_port2),
      boy_disembark_port2 = as.integer(boy_disembark_port2),
      girl_disembark_port2 = as.integer(girl_disembark_port2),
      adult_disembark_port2 = as.integer(adult_disembark_port2),
      child_disembark_port2 = as.integer(child_disembark_port2),
      infant_disembark_port2 = as.integer(infant_disembark_port2),
      male_disembark_port2 = as.integer(male_disembark_port2),
      female_disembark_port2 = as.integer(female_disembark_port2),
      slave_death_africa = as.integer(slave_death_africa),
      slave_death_passage = as.integer(slave_death_passage),
      slave_death_americas = as.integer(slave_death_americas),
      adult_embark_total = as.integer(adult_embark_total),
      child_embark_total = as.integer(child_embark_total),
      male_embark_total = as.integer(male_embark_total),
      female_embark_total = as.integer(female_embark_total),
      total_embarked_slaves = as.integer(total_embarked_slaves),
      total_embarked_age = as.integer(total_embarked_age),
      total_embarked_gender = as.integer(total_embarked_gender),
      pct_men_embark = as.numeric(pct_men_embark),
      pct_women_embark = as.numeric(pct_women_embark),
      pct_boy_embark = as.numeric(pct_boy_embark),
      pct_girl_embark = as.numeric(pct_girl_embark),
      pct_child_embark = as.numeric(pct_child_embark),
      pct_male_embark = as.numeric(pct_male_embark),
      adult_death_passage = as.integer(adult_death_passage),
      child_death_passage = as.integer(child_death_passage),
      male_death_passage = as.integer(male_death_passage),
      female_death_passage = as.integer(female_death_passage),
      adult_disembark_total = as.integer(adult_disembark_total),
      child_disembark_total = as.integer(child_disembark_total),
      male_disembark_total = as.integer(male_disembark_total),
      female_disembark_total = as.integer(female_disembark_total),
      total_landed_slaves = as.integer(total_landed_slaves),
      total_landed_age = as.integer(total_landed_age),
      total_landed_gender = as.integer(total_landed_gender),
      pct_men_landed = as.numeric(pct_men_landed),
      pct_women_landed = as.numeric(pct_women_landed),
      pct_boy_landed = as.numeric(pct_boy_landed),
      pct_girl_landed = as.numeric(pct_girl_landed),
      pct_child_landed = as.numeric(pct_child_landed),
      pct_male_landed = as.numeric(pct_male_landed),
      men_arrival_total = as.integer(men_arrival_total),
      women_arrival_total = as.integer(women_arrival_total),
      boy_arrival_total = as.integer(boy_arrival_total),
      girl_arrival_total = as.integer(girl_arrival_total),
      adult_arrival_total = as.integer(adult_arrival_total),
      child_arrival_total = as.integer(child_arrival_total),
      male_arrival_total = as.integer(male_arrival_total),
      female_arrival_total = as.integer(female_arrival_total),
      total_arrival_slaves = as.integer(total_arrival_slaves),
      total_arrival_age = as.integer(total_arrival_age),
      total_arrival_gender = as.integer(total_arrival_gender),
      pct_men_arrival = as.numeric(pct_men_arrival),
      pct_women_arrival = as.numeric(pct_women_arrival),
      pct_boy_arrival = as.numeric(pct_boy_arrival),
      pct_girl_arrival = as.numeric(pct_girl_arrival),
      pct_child_arrival = as.numeric(pct_child_arrival),
      pct_male_arrival = as.numeric(pct_male_arrival),
      slave_death_total_derived = as.integer(slave_death_total_derived),
      slave_death_passage_derived = as.integer(slave_death_passage_derived), 
      slave_mortality_rate = as.numeric(slave_mortality_rate),
      avg_slave_price_jamaica = as.numeric(avg_slave_price_jamaica),
      
      ## voyages_sources
      source_a = as.character(source_a),
      source_b = as.character(source_b),
      source_c = as.character(source_c),
      source_d = as.character(source_d),
      source_e = as.character(source_e),
      source_f = as.character(source_f),
      source_g = as.character(source_g),
      source_h = as.character(source_h),
      source_i = as.character(source_i),
      source_j = as.character(source_j),
      source_k = as.character(source_k),
      source_l = as.character(source_l),
      source_m = as.character(source_m),
      source_n = as.character(source_n),
      source_o = as.character(source_o),
      source_p = as.character(source_p),
      source_q = as.character(source_q),
      source_r = as.character(source_r)
    )
}

### Check data types after conversion
str(voyages_dataset)

# ── End of 04_slave_voyages_convert_data_types.R ──